### ISSUE TITLE
Enemies cannot gain Block

### ISSUE THREAD

**Issue by Vesper-arch** [Vesper-arch/Slay-The-Spire-in-Python#21]
The `Enemy.blocking()` function runs but no Block is applied. 
To see:
Seed: 65
Keystrokes: 3, 2 (Use Strike on Green Louse)
Expected Result: Green Louse takes 6 damage and gains 3 Block from Curl Up.
Actual Result: Green Louse takes 6 damage but gains no Block despite the corresponding function running.

**Comment by miketwo** [comment]
[The offending line is 462](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/blob/main/entities.py#L462):
```python
target.block = 0
```
Easy to fix by removing, but I don't know why it's there, so I don't know what removing might break...

**Comment by Vesper-arch** [comment]
Oof, I don't even know what I was thinking when writing that. I'll test out removing it and go from there.

**Comment by Vesper-arch** [comment]
Ok, that line was there to get the effect of block actually reducing damage. The reason why it didn't work was because it was being applied before `target.block = 0`, therefore negating it. However, Block that enemies apply to themselves still doesn't count.

**Comment by Vesper-arch** [comment]
Ok, that line was there to get the effect of block actually reducing damage. The reason why it didn't work was because it was being applied before `target.block = 0`, therefore negating it. However, Block that enemies apply to themselves still doesn't count.

**Comment by Vesper-arch** [comment]
Ok, Block can be applied by enemies but it doesn't decrease when dealt damage to

**Comment by Vesper-arch** [comment]
It's fixed now?
