### ISSUE TITLE
Package project with `pyinstaller`

### ISSUE THREAD

**Issue by Vesper-arch** [Vesper-arch/Slay-The-Spire-in-Python#26]
Replit recently removed the ability for Repls to be run outside of the editor without deploying them first, which requires a subscription. So, I instead want to use Flask to deploy the project to a website. This will require an intro sequence and some other stuff but I know the basics of using Flask as of 5 minutes ago.

**Comment by miketwo** [comment]
Flask can server request/response over HTTP, but it would take a significant amount of work to convert a console app. You'd be trying to host an entire interactive Python interpreter, or rewriting everything in javascript.

Also, just fyi, `pyproject.toml` and `poetry.lock` are not Replit things -- those are how depedencies (like ansimarkup) get installed.

**Comment by Vesper-arch** [comment]
What would be a doable way to host the app where people can play it without having to go through many technical things? I thought those were Replit files because they only got installed once I imported the project to Replit.

**Comment by miketwo** [comment]
And another option (just to list them all) might be to jump onto a project that already has a deployable web presense, like [this one](https://github.com/oskarrough/slaytheweb?tab=readme-ov-file). You'd be coding in javscript, but you'd skip over a bunch of the really hard stuff, like setting up a project and hosting/deploying it.

**Comment by Vesper-arch** [comment]
Oof, I think I'll go with `pyinstaller`. That seems relatively like the most simple setup and all people need is the ability to install files. How would I start off using that?
Honestly jumping to another project is the last thing on my mind, I want to continue working on this to learn Python.

**Comment by miketwo** [comment]
Unfortunately never used it. Follow the docs and google if something doesn't work.

**Comment by Vesper-arch** [comment]
Ok!

**Comment by miketwo** [comment]
Though I do suggest bringing back the `pyproject.toml` and lock file -- it may need those to figure out dependencies.

**Comment by Vesper-arch** [comment]
Would just restoring the files be enough or would I have to change some things?
