### ISSUE TITLE
`fresh_effects` not in Enemy

### ISSUE THREAD

**Issue by miketwo** [Vesper-arch/Slay-The-Spire-in-Python#28]
Off the following lines:
```python
if 'Enemy' in str(user):
   target.fresh_effects.append(effect_name)
```
... I received this error from `test_enemy.py`:
```python
E               AttributeError: 'Cultist' object has no attribute 'fresh_effects'
```

I will see if I can add CI/CD to my fork. If it works, I'll show you what that means.

**Comment by Vesper-arch** [comment]
Pull requests didn't work but I got the commits with `git cherry-pick`. Also, how do I delete the issue branch? I tried `git branch -d [branch_name]` but it still shows up on GitHub.

**Comment by miketwo** [comment]
`git branch -d` deletes the local copy of the branch. To delete GitHub's copy, you have to use `git push origin --delete [branchname]`

It's a weird syntax because the old way of doing it was to abuse the [refspec](https://git-scm.com/docs/git-push#Documentation/git-push.txt-ltrefspecgt82308203) in the push command. Git lets you push a branch onto one with a different name. For example, you could do `git push origin branchA:branchB` -- that means "push my branchA onto the remote one called branchB." But if you do it with a blank space for branchA, it would delete it, because the source was blank. So `git push origin :branchB` would delete branchB. 

Anyway, all that history is pointless. Just use `--delete`.
