### ISSUE TITLE
Hypnotizing Colored Mushrooms event cannot be coded due to the requirement of the `combat` function.

### ISSUE THREAD

**Issue by Vesper-arch** [Vesper-arch/Slay-The-Spire-in-Python#31]
One of the event's options causes a combat encounter to start but the `combat` function cannot be used without importing it first, which causes a circular import error because `events` is also imported to `main`.

**Comment by miketwo** [comment]
Push a branch with the problem and I'll take a look.

**Comment by Vesper-arch** [comment]
Do you mean actually code it and commit it?

**Comment by miketwo** [comment]
On a branch, yeah, not on `main`. Do you know how?

```bash
# ...from a clean directory (git status shows no uncommitted changes)
git checkout -b new_branch
# (change the code)
git commit -am "circular error"                             # commit changes
git push --set-upstream origin new_branch         # push to github
```

**Comment by miketwo** [comment]
Best guess without seeing the code is that you can probably do dependency injection. Call the event with `some_event(..., combat_function)` -- and the event never has to import it, just has to call the function.

**Comment by Vesper-arch** [comment]
I just made a new branch and started working on it but I didn't know about the rest

**Comment by Vesper-arch** [comment]
The problem I have is that no other event so far has a parameter, so I would have to somehow check if an event function has a parameter or not.

**Comment by Vesper-arch** [comment]
> On a branch, yeah, not on `main`. Do you know how?
> 
> ```shell
> # ...from a clean directory (git status shows no uncommitted changes)
> git checkout -b new_branch
> # (change the code)
> git commit -am "circular error"                             # commit changes
> git push --set-upstream origin new_branch         # push to github
> ```

I did that and deleted the new branch but it doesn't look like it actually committed them to github

**Comment by miketwo** [comment]
>and deleted the new branch

Not sure I understand. Did the push command work? Why would you be deleting any branches?

**Comment by Vesper-arch** [comment]
I thought the push command committed it to the main branch of GitHub and deleted it because I thought I didn't need the issue branch anymore

**Comment by Vesper-arch** [comment]
So, I'll have to redo the work I did because I deleted all of the changes I made along with the branch not knowing that they weren't committed to main.

**Comment by miketwo** [comment]
You can probably get it from the reflog! `git reflog show` will show a bunch of commits -- if you can find the matching one to the branch you can do a checkout of it. Find it before it expires!

**Comment by Vesper-arch** [comment]
well, I already added it back in the (stashed) uncommitted changes on main so I can just commit it after I add a the rest of the act 1 events.

**Comment by Vesper-arch** [comment]
What is the reflog though? Just for future reference.

**Comment by miketwo** [comment]
It's a history of any time the branch HEAD moves. So when you make a commit, or switch branches, or stash anything, or reset to a different commit, git stores a reference in the reflog. It gets cleaned up regularly, but if you accidently delete a branch or royally f' up a merge, the reflog can get you back.

**Comment by Vesper-arch** [comment]
Alright, that seems pretty useful. Thanks!
