### ISSUE TITLE
Most uses of `list_input()` don't handle error condition properly

### ISSUE THREAD

**Issue by miketwo** [Vesper-arch/Slay-The-Spire-in-Python#38]
`list_input()` looks like this:
```python
    def list_input(self, input_string: str, array: list) -> int | None:
        try:
            ansiprint(input_string, end='')
            option = int(input()) - 1
            array[option] = array[option] # Checks that the number is in range but doesn't really do anything
        except (ValueError, IndexError):
            return None
        return option
```

So it returns a number or None. But lots of usages of it look either like this:
```python
option = view.list_input(...)
if player.deck[option].get("Upgraded") is True:
```
... which would fail on `option=None`, or this:

```python
upgrade_card = view.list_input(...)
if not upgrade_card or ...
```

... which can't tell the difference between `upgrade_card=0` and `upgrade_card=None`.

Suggest putting all validation (and looping to ask the user again) inside a single function, so it only ever returns a valid choice. It would need to be able to redisplay possible choices and understand what's valid, so it could keep asking until the user gets it right. But that would fix some ~20 bugs probably.

**Comment by Vesper-arch** [comment]
So far I'm struggling with ANSI codes for the console. I am trying to make it so that if the choice you inputted breaks 1 or more rules it prints **after where you typed the input** what rules it violates, then clear the line and start the input again.

**Comment by Vesper-arch** [comment]
I don't know how to test this in isolation quickly so if you know anything about it, that would be great.

**Comment by Vesper-arch** [comment]
![helper py - Slay-The-Spire-in-Python  Dev Container_ Python 3  - Visual Studio Code 1_18_2024 8_54_14 PM](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/assets/137581120/f31f4609-2ee3-4240-824c-8d8bbd2049a8)
This is what I got so far

**Comment by miketwo** [comment]
Push a branch so I can run it and comment/edit. 

This is the sequence on the command line:

```bash
git checkout -b fix_list_input main     # creates a new branch from main

while developing:
   (make changes)
   git status                                          # shows changed files
   git add file1 file2 file3                           # add changed files to commit staging area
   git commit -m "some message about the changes"      # commit them

# once you're done or want some help
git push -u origin fix_list_input                      # pushes a branch to github
```

You can do this in VSCode or other gui's. I use `git gui` and `gitk` because they come with `git`. But that makes it easier for me to help.

**Comment by miketwo** [comment]
Just looking at the screenshot, I think you might be trying to do too much in one function? All the different conditions are specific to various **callers** of the `list_input()` function, who are separate from each other, but this code ties them together. (The caller that is concerned about whether a choice is Removable doesn't really care if the choice is Upgradeable, but the Upgradeable code runs on the card anyway.) It means you'll forever be coming back here to change the conditions as different callers use it, and that all conditions will have to be computable for all cards. 

You want to be able to write this once and be done. I suggest **pushing the validation logic outside the function**. Something like:
```python
def display_cards_and_choose(cards: list[dict], prompt: str, validator: Callable[[dict], bool]) -> int:
    '''
    Display a list of cards and prompt the user to choose one.
    :param cards: A list of cards to choose from.
    :param prompt: The prompt to display.
    :param validator: A function that takes a card and returns True if it is a valid choice. Used for greying out invalid cards and validating the user selection.
    '''
```

(You may need more args, but just to illustrate the point). So then, if I want to show cards but grey out and disallow anything that's not a `Skill`, I can do this as a caller:

```python
skill_validator = lambda card: card.get('Type') == 'Skill'
chosen_card = display_cards_and_choose(cards, "Pick a Skill", skill_validator)
```

So now, each caller gets to decide what's valid, and inside `display_cards_and_choose`, it doesn't really care why, it's going to just use the validation function to figure out what's valid or not. (You could make the validation functions also return a reason, if you want to display that.)

So now, validation functions can be tested by themselves and you'll only ever get back a valid choice from `display_cards_and_choose`. 

And if you need some complicated validation, you can create that on the fly. For example, "only Power or Attack cards with more than the player's energy, and also any card that starts with 'D'" would be:

```python
def special_validator(card):
  return card.get('Type') in ('Attack','Power') and \
         isinstance(card.get('Energy'), int) and card.get('Energy') <= player.energy or \
         card.get('Name').startswith('D')
chosen_card = display_cards_and_choose(cards, "Pick a Card", special_validator)
```

**Comment by Vesper-arch** [comment]
Ok, just published the branch. I love github desktop :)

**Comment by miketwo** [comment]
Did you commit anything to that branch? [The branches seem to be the same](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/compare/list_input_plus?expand=1).

**Comment by Vesper-arch** [comment]
Oh, forgot to commit what I had, gimme a sec

**Comment by Vesper-arch** [comment]
K, done
