### ISSUE TITLE
list_input() specific to cards, but used for other things

### ISSUE THREAD

**Issue by miketwo** [Vesper-arch/Slay-The-Spire-in-Python#44]
### Background
`helper.Displayer.list_input()` is written for cards -- it uses these two methods:

- `view_piles()`, whose doc says `"Prints a numbered list of all the cards in a certain pile"`, and
- `upgrade_preview()`, which says `"Print all of the cards in a given pile with their upgraded stats shown." `

...so the assumption that `list_input` is dealing with cards.

### Problem
However, `list_input()` is used to choose relics [here](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/blob/07f26ba308672fd36db9ec534072a4f51b55ec81/helper.py#L281), and to choose potions ([here](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/blob/07f26ba308672fd36db9ec534072a4f51b55ec81/helper.py#L315) and [here](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/blob/07f26ba308672fd36db9ec534072a4f51b55ec81/helper.py#L325)). These invocations likely fail because neither of them match the signature of a card.

### Options
Having different displayers for potions, relics, and cards (and other choices?) is not necessarily bad. They might be different enough to warrant that. (In fact, `view_potions()` and `view_relics()` already exist). So there's probably two solutions: 

1. You could create a separate `list_input()` for different types. So like a `list_input_cards()` and `list_input_potions()`.
2. You could create a more-generic `list_input()` that takes in a display function, similar to the validator function. So the caller is basically saying: "Here's a list of things, a function for displaying each thing, and a function for validating each thing -- please get the user's choice". And `list_input()` focuses just on the user's choice, and not on the specifics of displaying or validating.

**Comment by Vesper-arch** [comment]
Once this is solved I'll start packaging it with pyinstaller
