### ISSUE TITLE
Figure out how to prevent the exe's from closing on crashing for debugging purposes.

### ISSUE THREAD

**Issue by Vesper-arch** [Vesper-arch/Slay-The-Spire-in-Python#59]
I haven't found any documentation on how to fix this. All I find is how to stop it closing immediately which is not what I want.

**Comment by miketwo** [comment]
Unfortunately, that's the natural behaviour in windows for console applications.

If you open `cmd` first, and then run it from the console, it won't close.

Alternatively, you might be able to hack it by having a try/except at the outmost edge of the program catch all exceptions (except Ctrl-C), and then asking for input() so it hangs.

**Comment by Vesper-arch** [comment]
Would that still show the error?

**Comment by miketwo** [comment]
Yeah you just print it first with the full traceback before asking for input.

**Comment by Vesper-arch** [comment]
How do you print the full traceback?
