### ISSUE TITLE
Get back to working?

### ISSUE THREAD

**Issue by miketwo** [vesper-arch/Slay-the-Spire-in-Python#71]
The `main` branch seems to be busted. Maybe let's get it back to working and then try doing smaller, incremental updates?

**Comment by Vesper-arch** [comment]
Sounds good to me. Also where were you? Its been a while lmao

**Comment by Vesper-arch** [comment]
Also i just fully switched to linux so it may be a bit till my setup is back up and running

**Comment by miketwo** [comment]
Got divorced. Lost a house. Bought a house. It's been a ride. 

Pro-tip: Prenuptial agreement. Would've helped a lot.

**Comment by Vesper-arch** [comment]
Damn dude. Sorry i thought you just lost interest or smth.

**Comment by vesper-arch** [comment]
![image](https://github.com/user-attachments/assets/b3b85586-01b9-4c89-9a2f-e2efbe3c5e4e)
we're so back

**Comment by vesper-arch** [comment]
@miketwo should i just nuke the combat and items branches? I figure changing stuff in main right now will make it much harder to merge later on

**Comment by vesper-arch** [comment]
Maybe even just revert to just when the message bus was added

**Comment by vesper-arch** [comment]
yeah ima do that

**Comment by vesper-arch** [comment]
update: i know why i didn't want to work on this before

**Comment by vesper-arch** [comment]
thats why i'm going back to my first implementation but will be adding stuff in smaller prs
